/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  mySidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'What is Intuita?',
    },
    {
        type: 'category',
        label: 'Intuita VS Code Extension',
        items: [
          'vs-code-extension/getting-started-overview',
          'vs-code-extension/running-codemods',
          'vs-code-extension/importing-codemods',
        ],
    },
    {
      type: 'category',
      label: 'Codemod Studio',
      items: [
        'codemod-studio/getting-started-overview',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/our-community',
        'contributing/roadmap',
      ],
    },
    
  ],
   
};

module.exports = sidebars;
